sudo: required

language: generic

addons:
  artifacts:
    s3_region: eu-west-1
    paths:
      - tests/codeceptjs/output

env:
  - SELENIUM_BROWSER=chrome
  - SELENIUM_BROWSER=firefox

services:
  - docker

before_script:
  - cd tests
  - docker-compose up -d node $SELENIUM_BROWSER
  - docker-compose run --rm node yarn install
  - docker-compose run --rm node yarn build
  - docker-compose ps

script:
  - docker-compose run --rm codeceptjs codeceptjs run-multiple basic:$SELENIUM_BROWSER --steps
